// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srxbztnlitspvqrzqmvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyeGJ6dG5saXRzcHZxcnpxbXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTM0MzksImV4cCI6MjA1OTgyOTQzOX0.UvkU71q1_7UFraVgXfp7S2AFWsHUiiOToeMjdCsX5kE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);