name: 🚀 Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v3

      - name: 📂 Upload per SFTP zu IONOS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}       # z.B. access-5017105000.webspace-host.com
          username: ${{ secrets.SFTP_USERNAME }}   # z.B. a744476
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "./*"
          target: "/" # Ziel: Webverzeichnis, das live ist (bei deinem SFTP-Zugang entspricht "/" dem /htdocs/)
          strip_components: 1
