name: 🚀 Deploy to IONOS via SFTP

on:
  push:
    branches:
      - main  # Falls dein Haupt Branch anders heißt, ändere "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v3

      - name: 📂 Upload per SFTP zu IONOS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}       # 👈 Holt den SFTP-Server aus GitHub Secrets
          username: ${{ secrets.SFTP_USERNAME }} # 👈 Holt den Benutzernamen aus GitHub Secrets
          password: ${{ secrets.SFTP_PASSWORD }} # 👈 Holt das Passwort aus GitHub Secrets
          source: "./*"
          target: "/"
          strip_components: 1
